language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
addons:
  sonarcloud:
    organization: "sudhir05-github"
    token:
      secure: "ab9e5b67637d6c13396cb00f17a37d8e9e27ab66"
install: npm install
script:
- sonar-scanner
- npm test