language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
addons:
  sonarcloud:
    organization: sudhir05-github
    token:
      secure: mg+RomJWF6aQpGkx7psks5udFgPHIY6iKhCL10l4rXl3+3OBrsSueaMWO0v9gKqgKxykWTq6xO4RzGIitQ050Isaf0b37hXdhEuo50oDbk/A89x7jEiKSL3YyogBZfvgGb+agSzfFGkFrcWewqocPfjJjDh70nXu0wbNR4UnyrlDurQLAp9cNU6AucxscNjYcLtlq7uQsXXSoC/1SZ+q/ysdN7TWFOpaGIpVImEYDYy54f5KHGvcd6nlgvKL4j399jcjmMbudsCGjc+9jVFkRu5Jfqh9xcJoYk6cNj7wSos6M7dU7zCZMqegJjfsi0xFiiUnMsHFvCC+0JtekjE9tV69seJhnKp8O7pHA5l823jmCzsRATNdI6SykyddZilmMJH/olsWwZLKeGeY06wgyKEr4ul5MtObDUfx0JaW9GbYxthfJqlQNbgr8O+Ruoj02lmMQURnIB1X3tr+DFFrgms4VDf025+GyDVJpKNWEW8MOMJeWnXliVpitavGaGv1ymOt6twov8ImtZTGQCXMHkBiXQBxdelIaIuE3h8ECSHJpwa5bX+iax9grYODKH4MomaE25mPN7hKYtruKgGA6CpffD79rRHFYT55vaYdFQsvVeUYrvjws8XBn+U7cLdmtFUwSBi06sqopxhj8eMj/seApRN6WAi2qFCCBkLTVZA=
install: npm install
script:
- sonar-scanner
- npm test