language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
services:
  - docker
addons:
  sonarcloud:
    organization: "sudhir05-github"
    token: ${SONAR_TOKEN}
install: npm install
script:
- sonar-scanner
- npm test
- docker build --tag "$IMAGE_NAME" .
env:
  global:
    - IMAGE_NAME=anztech