language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
addons:
  sonarcloud:
    organization: sudhir05-github
    token:
      secure: ddda4fa968c7613fc72720855f836db2d4f565aa
install: npm install
script:
- sonar-scanner
- npm test