language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
addons:
  sonarcloud:
    organization: "sudhir05-github"
    token: ${SONAR_TOKEN}
install: npm install
script:
- sonar-scanner
- npm test